document.addEventListener("DOMContentLoaded", function() {
    const el_admin_dashboard_btn = document.getElementById("admin-dashboard-btn");
    if (el_admin_dashboard_btn) el_admin_dashboard_btn.addEventListener("click", function(event) { if(window.promptAdminAccess) window.promptAdminAccess() });
    const el_mobile_filter_btn = document.getElementById("mobile-filter-btn");
    if (el_mobile_filter_btn) el_mobile_filter_btn.addEventListener("click", function(event) { document.querySelector('.filter-sidebar').classList.add('mobile-open'); if(document.querySelector('.cupid-actions')) document.querySelector('.cupid-actions').style.display = 'none'; });
    const el_nav_verify_identity_btn = document.getElementById("nav-verify-identity-btn");
    if (el_nav_verify_identity_btn) el_nav_verify_identity_btn.addEventListener("click", function(event) { window.openVerificationModal && window.openVerificationModal() });
    const el_nav_settings_btn = document.getElementById("nav-settings-btn");
    if (el_nav_settings_btn) el_nav_settings_btn.addEventListener("click", function(event) { window.openSettingsModal() });
    const el_nav_premium_btn = document.getElementById("nav-premium-btn");
    if (el_nav_premium_btn) el_nav_premium_btn.addEventListener("click", function(event) { window.openPremiumModal && window.openPremiumModal() });
    const el_close_premium_modal_btn = document.getElementById("close-premium-modal-btn");
    if (el_close_premium_modal_btn) el_close_premium_modal_btn.addEventListener("click", function(event) { window.closePremiumModal && window.closePremiumModal() });
    const el_btn_resend_verification = document.getElementById("btn-resend-verification");
    if (el_btn_resend_verification) el_btn_resend_verification.addEventListener("click", function(event) { window.resendVerificationEmail() });
    const el_dynamic_btn_1 = document.getElementById("dynamic-btn-1");
    if (el_dynamic_btn_1) el_dynamic_btn_1.addEventListener("click", function(event) { window.location.reload() });
    const el_dynamic_btn_2 = document.getElementById("dynamic-btn-2");
    if (el_dynamic_btn_2) el_dynamic_btn_2.addEventListener("click", function(event) { if(window.secureYatramoreLogout) window.secureYatramoreLogout(); else { window.pb.authStore.clear(); window.location.reload(); } });
    const el_dynamic_btn_3 = document.getElementById("dynamic-btn-3");
    if (el_dynamic_btn_3) el_dynamic_btn_3.addEventListener("click", function(event) { window.revokeDeletionRequest() });
    const el_dynamic_btn_4 = document.getElementById("dynamic-btn-4");
    if (el_dynamic_btn_4) el_dynamic_btn_4.addEventListener("click", function(event) { if(window.secureYatramoreLogout) window.secureYatramoreLogout(); else { window.pb.authStore.clear(); window.location.reload(); } });
    const el_desktop_filter_toggle = document.getElementById("desktop-filter-toggle");
    if (el_desktop_filter_toggle) el_desktop_filter_toggle.addEventListener("click", function(event) { document.getElementById('filter-sidebar-content').classList.toggle('expanded'); document.getElementById('desktop-filter-icon').style.transform = document.getElementById('filter-sidebar-content').classList.contains('expanded') ? 'rotate(180deg)' : 'rotate(0deg)'; });
    const el_dynamic_btn_5 = document.getElementById("dynamic-btn-5");
    if (el_dynamic_btn_5) el_dynamic_btn_5.addEventListener("click", function(event) { document.querySelector('.filter-sidebar').classList.remove('mobile-open'); if(document.querySelector('.cupid-actions')) document.querySelector('.cupid-actions').style.display = ''; });
    const el_btn_pass = document.getElementById("btn-pass");
    if (el_btn_pass) el_btn_pass.addEventListener("click", function(event) { triggerPass() });
    const el_btn_superlike = document.getElementById("btn-superlike");
    if (el_btn_superlike) el_btn_superlike.addEventListener("click", function(event) { triggerSuperLike() });
    const el_btn_like = document.getElementById("btn-like");
    if (el_btn_like) el_btn_like.addEventListener("click", function(event) { triggerLike() });
    const el_edit_modal = document.getElementById("edit-modal");
    if (el_edit_modal) el_edit_modal.addEventListener("click", function(event) { if(event.target === this && window.canCloseEditModal !== false) this.classList.remove('active') });
    const el_dynamic_btn_6 = document.getElementById("dynamic-btn-6");
    if (el_dynamic_btn_6) el_dynamic_btn_6.addEventListener("click", function(event) { document.getElementById('edit-modal').classList.remove('active') });
    const el_dynamic_btn_7 = document.getElementById("dynamic-btn-7");
    if (el_dynamic_btn_7) el_dynamic_btn_7.addEventListener("click", function(event) { document.getElementById('profile-photo-1').click() });
    const el_dynamic_btn_8 = document.getElementById("dynamic-btn-8");
    if (el_dynamic_btn_8) el_dynamic_btn_8.addEventListener("click", function(event) { document.getElementById('profile-photo-2').click() });
    const el_dynamic_btn_9 = document.getElementById("dynamic-btn-9");
    if (el_dynamic_btn_9) el_dynamic_btn_9.addEventListener("click", function(event) { document.getElementById('profile-photo-3').click() });
    const el_dynamic_btn_10 = document.getElementById("dynamic-btn-10");
    if (el_dynamic_btn_10) el_dynamic_btn_10.addEventListener("click", function(event) { document.getElementById('profile-photo-4').click() });
    const el_dynamic_btn_11 = document.getElementById("dynamic-btn-11");
    if (el_dynamic_btn_11) el_dynamic_btn_11.addEventListener("click", function(event) { window.closeSettingsModal() });
    const el_dynamic_btn_12 = document.getElementById("dynamic-btn-12");
    if (el_dynamic_btn_12) el_dynamic_btn_12.addEventListener("click", function(event) { window.closeSettingsModal() });
    const el_dynamic_btn_13 = document.getElementById("dynamic-btn-13");
    if (el_dynamic_btn_13) el_dynamic_btn_13.addEventListener("click", function(event) { window.closeSettingsModal(); window.openEditProfileModal(true); });
    const el_dynamic_btn_14 = document.getElementById("dynamic-btn-14");
    if (el_dynamic_btn_14) el_dynamic_btn_14.addEventListener("click", function(event) { window.closeSettingsModal(); window.openChangeEmailModal(); });
    const el_dynamic_btn_15 = document.getElementById("dynamic-btn-15");
    if (el_dynamic_btn_15) el_dynamic_btn_15.addEventListener("click", function(event) { window.closeSettingsModal(); window.openBlockedUsersModal(); });
    const el_dynamic_btn_16 = document.getElementById("dynamic-btn-16");
    if (el_dynamic_btn_16) el_dynamic_btn_16.addEventListener("click", function(event) { window.closeSettingsModal(); window.requestAccountDeletion(); });
    const el_dynamic_btn_17 = document.getElementById("dynamic-btn-17");
    if (el_dynamic_btn_17) el_dynamic_btn_17.addEventListener("click", function(event) { window.closeAccountDeletionModal() });
    const el_dynamic_btn_18 = document.getElementById("dynamic-btn-18");
    if (el_dynamic_btn_18) el_dynamic_btn_18.addEventListener("click", function(event) { window.closeAccountDeletionModal() });
    const el_dynamic_btn_19 = document.getElementById("dynamic-btn-19");
    if (el_dynamic_btn_19) el_dynamic_btn_19.addEventListener("click", function(event) { window.closeAccountDeletionModal() });
    const el_dynamic_btn_20 = document.getElementById("dynamic-btn-20");
    if (el_dynamic_btn_20) el_dynamic_btn_20.addEventListener("click", function(event) { window.confirmAccountDeletion() });
    const el_dynamic_btn_21 = document.getElementById("dynamic-btn-21");
    if (el_dynamic_btn_21) el_dynamic_btn_21.addEventListener("click", function(event) { window.closeBlockedUsersModal() });
    const el_dynamic_btn_22 = document.getElementById("dynamic-btn-22");
    if (el_dynamic_btn_22) el_dynamic_btn_22.addEventListener("click", function(event) { window.closeBlockedUsersModal() });
    const el_dynamic_btn_23 = document.getElementById("dynamic-btn-23");
    if (el_dynamic_btn_23) el_dynamic_btn_23.addEventListener("click", function(event) { window.closeChangeEmailModal() });
    const el_dynamic_btn_24 = document.getElementById("dynamic-btn-24");
    if (el_dynamic_btn_24) el_dynamic_btn_24.addEventListener("click", function(event) { window.closeChangeEmailModal() });
    const el_verify_identity_modal = document.getElementById("verify-identity-modal");
    if (el_verify_identity_modal) el_verify_identity_modal.addEventListener("click", function(event) { if(event.target === this) this.classList.remove('active') });
    const el_dynamic_btn_25 = document.getElementById("dynamic-btn-25");
    if (el_dynamic_btn_25) el_dynamic_btn_25.addEventListener("click", function(event) { document.getElementById('verify-identity-modal').classList.remove('active') });
    const el_dynamic_btn_26 = document.getElementById("dynamic-btn-26");
    if (el_dynamic_btn_26) el_dynamic_btn_26.addEventListener("click", function(event) { document.getElementById('verification-id-input').click() });
    const el_dynamic_btn_27 = document.getElementById("dynamic-btn-27");
    if (el_dynamic_btn_27) el_dynamic_btn_27.addEventListener("click", function(event) { document.getElementById('verification-selfie-input').click() });
    const el_upload_id_btn = document.getElementById("upload-id-btn");
    if (el_upload_id_btn) el_upload_id_btn.addEventListener("click", function(event) { window.submitVerification() });
    const el_dynamic_btn_28 = document.getElementById("dynamic-btn-28");
    if (el_dynamic_btn_28) el_dynamic_btn_28.addEventListener("click", function(event) { document.getElementById('block-modal').style.display = 'none' });
    const el_dynamic_btn_29 = document.getElementById("dynamic-btn-29");
    if (el_dynamic_btn_29) el_dynamic_btn_29.addEventListener("click", function(event) { document.getElementById('block-modal').style.display = 'none' });
    const el_dynamic_btn_30 = document.getElementById("dynamic-btn-30");
    if (el_dynamic_btn_30) el_dynamic_btn_30.addEventListener("click", function(event) { document.getElementById('block-modal').style.display = 'none' });
    const el_dynamic_btn_31 = document.getElementById("dynamic-btn-31");
    if (el_dynamic_btn_31) el_dynamic_btn_31.addEventListener("click", function(event) { document.getElementById('report-modal').style.display = 'none' });
    const el_dynamic_btn_32 = document.getElementById("dynamic-btn-32");
    if (el_dynamic_btn_32) el_dynamic_btn_32.addEventListener("click", function(event) { document.getElementById('report-modal').style.display = 'none' });
    const el_dynamic_btn_33 = document.getElementById("dynamic-btn-33");
    if (el_dynamic_btn_33) el_dynamic_btn_33.addEventListener("click", function(event) { document.getElementById('swipe-limit-modal').style.display = 'none' });
    const el_dynamic_btn_34 = document.getElementById("dynamic-btn-34");
    if (el_dynamic_btn_34) el_dynamic_btn_34.addEventListener("click", function(event) { document.getElementById('swipe-limit-modal').style.display = 'none' });
    const el_dynamic_btn_35 = document.getElementById("dynamic-btn-35");
    if (el_dynamic_btn_35) el_dynamic_btn_35.addEventListener("click", function(event) { document.getElementById('swipe-limit-modal').style.display = 'none' });
    const el_chat_profile_modal = document.getElementById("chat-profile-modal");
    if (el_chat_profile_modal) el_chat_profile_modal.addEventListener("click", function(event) { if(event.target === this) this.classList.remove('active') });
    const el_dynamic_btn_36 = document.getElementById("dynamic-btn-36");
    if (el_dynamic_btn_36) el_dynamic_btn_36.addEventListener("click", function(event) { document.getElementById('chat-profile-modal').classList.remove('active') });
});